// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Nicolas Consigny <nicolas@ethereum.org>
// Generated by sphincs/generate-verifier.py from pinned upstream; do not edit.
// Terminal assembly uses scratch memory; intentionally NOT memory-safe.
pragma solidity ^0.8.28;
contract C13Verifier {
    function verify(bytes32 pkSeed, bytes32 pkRoot, bytes32 message, bytes calldata sig)
        external pure returns (bool valid)
    {
        assembly {
function chain(base, val, digit) -> result { switch digit
case 7 {
}
case 6 {
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
case 5 {
mstore(0x20, or(base, 5)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
case 4 {
mstore(0x20, or(base, 4)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 5)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
case 3 {
mstore(0x20, or(base, 3)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 4)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 5)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
case 2 {
mstore(0x20, or(base, 2)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 3)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 4)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 5)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
case 1 {
mstore(0x20, or(base, 1)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 2)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 3)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 4)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 5)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
case 0 {
mstore(0x20, or(base, 0)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 1)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 2)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 3)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 4)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 5)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
mstore(0x20, or(base, 6)) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)
}
result := val }
            let N_MASK := 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000
            if iszero(eq(sig.length, 3688)) {
                mstore(0x00, 0x08c379a000000000000000000000000000000000000000000000000000000000)
                mstore(0x04, 0x20)
                mstore(0x24, 18)
                mstore(0x44, "Invalid sig length")
                revert(0x00, 0x64)
            }
            if or(iszero(eq(pkSeed, and(pkSeed, N_MASK))), iszero(eq(pkRoot, and(pkRoot, N_MASK)))) {
                mstore(0x00, 0x08c379a000000000000000000000000000000000000000000000000000000000)
                mstore(0x04, 0x20)
                mstore(0x24, 18)
                mstore(0x44, "Invalid public key")
                revert(0x00, 0x64)
            }
            let seed := pkSeed
            let root := pkRoot
            mstore(0x00, seed)
            let R := and(calldataload(sig.offset), N_MASK)
            mstore(0x20, root)
            mstore(0x40, R)
            mstore(0x60, message)
            mstore(0x80, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)
            let digest := keccak256(0x00, 0xA0)
            let htIdx := and(shr(133, digest), 0x3FFFFF)
            let dVal := digest
            if and(shr(114, dVal), 0x7FFFF) { mstore(0x00, 0) return(0x00, 0x20) }
            let sigBase := sig.offset
            let idxLeaf0 := and(htIdx, 0x7FF)
            let idxTree0 := shr(11, htIdx)
            let forsBase := or(shl(128, idxTree0), or(shl(96, 3), shl(64, idxLeaf0)))
            {
                let treeIdx := and(shr(mul(0, 19), dVal), 0x7FFFF)
                let secretVal := and(calldataload(add(sigBase, add(16, shl(4, 0)))), N_MASK)
                let leafAdrs := or(forsBase, or(shl(19, 0), treeIdx))
                mstore(0x20, leafAdrs)
                mstore(0x40, secretVal)
                let node := and(keccak256(0x00, 0x60), N_MASK)
                let pathIdx := treeIdx
                let authPtr := add(sigBase, add(128, mul(0, 304)))
                {
                    let sibling := and(calldataload(add(authPtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(0, 1)), or(shl(sub(18, 0), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(1, 1)), or(shl(sub(18, 1), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(2, 1)), or(shl(sub(18, 2), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(3, 1)), or(shl(sub(18, 3), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(4, 1)), or(shl(sub(18, 4), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(5, 1)), or(shl(sub(18, 5), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(6, 1)), or(shl(sub(18, 6), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(7, 1)), or(shl(sub(18, 7), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(8, 1)), or(shl(sub(18, 8), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(9, 1)), or(shl(sub(18, 9), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(10, 1)), or(shl(sub(18, 10), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 11))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(11, 1)), or(shl(sub(18, 11), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 12))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(12, 1)), or(shl(sub(18, 12), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 13))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(13, 1)), or(shl(sub(18, 13), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 14))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(14, 1)), or(shl(sub(18, 14), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 15))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(15, 1)), or(shl(sub(18, 15), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 16))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(16, 1)), or(shl(sub(18, 16), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 17))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(17, 1)), or(shl(sub(18, 17), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 18))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(18, 1)), or(shl(sub(18, 18), 0), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
                mstore(add(0x80, shl(5, 0)), node)
            }
{
                let treeIdx := and(shr(mul(1, 19), dVal), 0x7FFFF)
                let secretVal := and(calldataload(add(sigBase, add(16, shl(4, 1)))), N_MASK)
                let leafAdrs := or(forsBase, or(shl(19, 1), treeIdx))
                mstore(0x20, leafAdrs)
                mstore(0x40, secretVal)
                let node := and(keccak256(0x00, 0x60), N_MASK)
                let pathIdx := treeIdx
                let authPtr := add(sigBase, add(128, mul(1, 304)))
                {
                    let sibling := and(calldataload(add(authPtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(0, 1)), or(shl(sub(18, 0), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(1, 1)), or(shl(sub(18, 1), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(2, 1)), or(shl(sub(18, 2), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(3, 1)), or(shl(sub(18, 3), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(4, 1)), or(shl(sub(18, 4), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(5, 1)), or(shl(sub(18, 5), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(6, 1)), or(shl(sub(18, 6), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(7, 1)), or(shl(sub(18, 7), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(8, 1)), or(shl(sub(18, 8), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(9, 1)), or(shl(sub(18, 9), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(10, 1)), or(shl(sub(18, 10), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 11))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(11, 1)), or(shl(sub(18, 11), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 12))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(12, 1)), or(shl(sub(18, 12), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 13))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(13, 1)), or(shl(sub(18, 13), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 14))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(14, 1)), or(shl(sub(18, 14), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 15))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(15, 1)), or(shl(sub(18, 15), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 16))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(16, 1)), or(shl(sub(18, 16), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 17))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(17, 1)), or(shl(sub(18, 17), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 18))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(18, 1)), or(shl(sub(18, 18), 1), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
                mstore(add(0x80, shl(5, 1)), node)
            }
{
                let treeIdx := and(shr(mul(2, 19), dVal), 0x7FFFF)
                let secretVal := and(calldataload(add(sigBase, add(16, shl(4, 2)))), N_MASK)
                let leafAdrs := or(forsBase, or(shl(19, 2), treeIdx))
                mstore(0x20, leafAdrs)
                mstore(0x40, secretVal)
                let node := and(keccak256(0x00, 0x60), N_MASK)
                let pathIdx := treeIdx
                let authPtr := add(sigBase, add(128, mul(2, 304)))
                {
                    let sibling := and(calldataload(add(authPtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(0, 1)), or(shl(sub(18, 0), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(1, 1)), or(shl(sub(18, 1), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(2, 1)), or(shl(sub(18, 2), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(3, 1)), or(shl(sub(18, 3), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(4, 1)), or(shl(sub(18, 4), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(5, 1)), or(shl(sub(18, 5), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(6, 1)), or(shl(sub(18, 6), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(7, 1)), or(shl(sub(18, 7), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(8, 1)), or(shl(sub(18, 8), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(9, 1)), or(shl(sub(18, 9), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(10, 1)), or(shl(sub(18, 10), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 11))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(11, 1)), or(shl(sub(18, 11), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 12))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(12, 1)), or(shl(sub(18, 12), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 13))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(13, 1)), or(shl(sub(18, 13), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 14))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(14, 1)), or(shl(sub(18, 14), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 15))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(15, 1)), or(shl(sub(18, 15), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 16))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(16, 1)), or(shl(sub(18, 16), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 17))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(17, 1)), or(shl(sub(18, 17), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 18))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(18, 1)), or(shl(sub(18, 18), 2), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
                mstore(add(0x80, shl(5, 2)), node)
            }
{
                let treeIdx := and(shr(mul(3, 19), dVal), 0x7FFFF)
                let secretVal := and(calldataload(add(sigBase, add(16, shl(4, 3)))), N_MASK)
                let leafAdrs := or(forsBase, or(shl(19, 3), treeIdx))
                mstore(0x20, leafAdrs)
                mstore(0x40, secretVal)
                let node := and(keccak256(0x00, 0x60), N_MASK)
                let pathIdx := treeIdx
                let authPtr := add(sigBase, add(128, mul(3, 304)))
                {
                    let sibling := and(calldataload(add(authPtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(0, 1)), or(shl(sub(18, 0), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(1, 1)), or(shl(sub(18, 1), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(2, 1)), or(shl(sub(18, 2), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(3, 1)), or(shl(sub(18, 3), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(4, 1)), or(shl(sub(18, 4), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(5, 1)), or(shl(sub(18, 5), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(6, 1)), or(shl(sub(18, 6), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(7, 1)), or(shl(sub(18, 7), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(8, 1)), or(shl(sub(18, 8), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(9, 1)), or(shl(sub(18, 9), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(10, 1)), or(shl(sub(18, 10), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 11))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(11, 1)), or(shl(sub(18, 11), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 12))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(12, 1)), or(shl(sub(18, 12), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 13))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(13, 1)), or(shl(sub(18, 13), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 14))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(14, 1)), or(shl(sub(18, 14), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 15))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(15, 1)), or(shl(sub(18, 15), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 16))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(16, 1)), or(shl(sub(18, 16), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 17))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(17, 1)), or(shl(sub(18, 17), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 18))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(18, 1)), or(shl(sub(18, 18), 3), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
                mstore(add(0x80, shl(5, 3)), node)
            }
{
                let treeIdx := and(shr(mul(4, 19), dVal), 0x7FFFF)
                let secretVal := and(calldataload(add(sigBase, add(16, shl(4, 4)))), N_MASK)
                let leafAdrs := or(forsBase, or(shl(19, 4), treeIdx))
                mstore(0x20, leafAdrs)
                mstore(0x40, secretVal)
                let node := and(keccak256(0x00, 0x60), N_MASK)
                let pathIdx := treeIdx
                let authPtr := add(sigBase, add(128, mul(4, 304)))
                {
                    let sibling := and(calldataload(add(authPtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(0, 1)), or(shl(sub(18, 0), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(1, 1)), or(shl(sub(18, 1), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(2, 1)), or(shl(sub(18, 2), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(3, 1)), or(shl(sub(18, 3), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(4, 1)), or(shl(sub(18, 4), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(5, 1)), or(shl(sub(18, 5), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(6, 1)), or(shl(sub(18, 6), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(7, 1)), or(shl(sub(18, 7), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(8, 1)), or(shl(sub(18, 8), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(9, 1)), or(shl(sub(18, 9), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(10, 1)), or(shl(sub(18, 10), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 11))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(11, 1)), or(shl(sub(18, 11), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 12))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(12, 1)), or(shl(sub(18, 12), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 13))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(13, 1)), or(shl(sub(18, 13), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 14))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(14, 1)), or(shl(sub(18, 14), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 15))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(15, 1)), or(shl(sub(18, 15), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 16))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(16, 1)), or(shl(sub(18, 16), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 17))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(17, 1)), or(shl(sub(18, 17), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 18))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(18, 1)), or(shl(sub(18, 18), 4), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
                mstore(add(0x80, shl(5, 4)), node)
            }
{
                let treeIdx := and(shr(mul(5, 19), dVal), 0x7FFFF)
                let secretVal := and(calldataload(add(sigBase, add(16, shl(4, 5)))), N_MASK)
                let leafAdrs := or(forsBase, or(shl(19, 5), treeIdx))
                mstore(0x20, leafAdrs)
                mstore(0x40, secretVal)
                let node := and(keccak256(0x00, 0x60), N_MASK)
                let pathIdx := treeIdx
                let authPtr := add(sigBase, add(128, mul(5, 304)))
                {
                    let sibling := and(calldataload(add(authPtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(0, 1)), or(shl(sub(18, 0), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(1, 1)), or(shl(sub(18, 1), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(2, 1)), or(shl(sub(18, 2), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(3, 1)), or(shl(sub(18, 3), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(4, 1)), or(shl(sub(18, 4), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(5, 1)), or(shl(sub(18, 5), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(6, 1)), or(shl(sub(18, 6), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(7, 1)), or(shl(sub(18, 7), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(8, 1)), or(shl(sub(18, 8), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(9, 1)), or(shl(sub(18, 9), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(10, 1)), or(shl(sub(18, 10), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 11))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(11, 1)), or(shl(sub(18, 11), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 12))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(12, 1)), or(shl(sub(18, 12), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 13))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(13, 1)), or(shl(sub(18, 13), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 14))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(14, 1)), or(shl(sub(18, 14), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 15))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(15, 1)), or(shl(sub(18, 15), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 16))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(16, 1)), or(shl(sub(18, 16), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 17))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(17, 1)), or(shl(sub(18, 17), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(authPtr, shl(4, 18))), N_MASK)
                    let parentIdx := shr(1, pathIdx)
                    mstore(0x20, or(forsBase, or(shl(32, add(18, 1)), or(shl(sub(18, 18), 5), parentIdx))))
                    let s := shl(5, and(pathIdx, 1))
                    mstore(xor(0x40, s), node)
                    mstore(xor(0x60, s), sibling)
                    node := and(keccak256(0x00, 0x80), N_MASK)
                    pathIdx := parentIdx
                }
                mstore(add(0x80, shl(5, 5)), node)
            }
            {
                let lastSecret := and(calldataload(add(sigBase, add(16, shl(4, 6)))), N_MASK)
                mstore(0x20, or(forsBase, shl(19, 6)))
                mstore(0x40, lastSecret)
                mstore(0x140, and(keccak256(0x00, 0x60), N_MASK))
            }
            mstore(0x20, or(shl(128, idxTree0), or(shl(96, 4), shl(64, idxLeaf0))))
            mcopy(0x40, 0x80, 224)
            let forsPk := and(keccak256(0x00, 0x120), N_MASK)
            let currentNode := forsPk
            let idxTree := htIdx
            let sigOff := 1952
            for { let layer := 0 } lt(layer, 2) { layer := add(layer, 1) } {
                let idxLeaf := and(idxTree, 0x7FF)
                idxTree := shr(11, idxTree)
                let wotsAdrs := or(shl(224, layer), or(shl(128, idxTree), shl(64, idxLeaf)))
                let countOff := add(sigOff, 688)
                let count := shr(224, calldataload(add(sigBase, countOff)))
                mstore(0x20, wotsAdrs)
                mstore(0x40, currentNode)
                mstore(0x60, count)
                let d := keccak256(0x00, 0x80)
let digitSum := and(d, 0x1ffffffffffffffffffffffffffffffff)
digitSum := add(and(digitSum, 0x71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7), and(shr(3, digitSum), 0x71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7))
digitSum := add(and(digitSum, 0xf03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f), and(shr(6, digitSum), 0xf03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f03f))
digitSum := add(and(digitSum, 0xfff000fff000fff000fff000fff000fff000fff000fff000fff000fff000fff), and(shr(12, digitSum), 0xfff000fff000fff000fff000fff000fff000fff000fff000fff000fff000fff))
digitSum := add(and(digitSum, 0xffff000000ffffff000000ffffff000000ffffff000000ffffff000000ffffff), and(shr(24, digitSum), 0xffff000000ffffff000000ffffff000000ffffff000000ffffff000000ffffff))
digitSum := add(and(digitSum, 0xffffffffffff000000000000ffffffffffff000000000000ffffffffffff), and(shr(48, digitSum), 0xffffffffffff000000000000ffffffffffff000000000000ffffffffffff))
digitSum := add(and(digitSum, 0xffffffffffffffff000000000000000000000000ffffffffffffffffffffffff), and(shr(96, digitSum), 0xffffffffffffffff000000000000000000000000ffffffffffffffffffffffff))
                if iszero(eq(digitSum, 208)) { mstore(0x00, 0) return(0x00, 0x20) }
                let wotsPtr := add(sigBase, sigOff)
                {
                    let digit := and(shr(mul(0, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 0))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 0))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 0)), val)
                }
{
                    let digit := and(shr(mul(1, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 1))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 1))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 1)), val)
                }
{
                    let digit := and(shr(mul(2, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 2))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 2))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 2)), val)
                }
{
                    let digit := and(shr(mul(3, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 3))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 3))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 3)), val)
                }
{
                    let digit := and(shr(mul(4, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 4))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 4))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 4)), val)
                }
{
                    let digit := and(shr(mul(5, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 5))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 5))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 5)), val)
                }
{
                    let digit := and(shr(mul(6, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 6))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 6))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 6)), val)
                }
{
                    let digit := and(shr(mul(7, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 7))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 7))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 7)), val)
                }
{
                    let digit := and(shr(mul(8, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 8))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 8))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 8)), val)
                }
{
                    let digit := and(shr(mul(9, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 9))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 9))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 9)), val)
                }
{
                    let digit := and(shr(mul(10, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 10))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 10))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 10)), val)
                }
{
                    let digit := and(shr(mul(11, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 11))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 11))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 11)), val)
                }
{
                    let digit := and(shr(mul(12, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 12))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 12))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 12)), val)
                }
{
                    let digit := and(shr(mul(13, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 13))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 13))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 13)), val)
                }
{
                    let digit := and(shr(mul(14, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 14))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 14))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 14)), val)
                }
{
                    let digit := and(shr(mul(15, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 15))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 15))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 15)), val)
                }
{
                    let digit := and(shr(mul(16, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 16))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 16))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 16)), val)
                }
{
                    let digit := and(shr(mul(17, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 17))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 17))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 17)), val)
                }
{
                    let digit := and(shr(mul(18, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 18))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 18))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 18)), val)
                }
{
                    let digit := and(shr(mul(19, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 19))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 19))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 19)), val)
                }
{
                    let digit := and(shr(mul(20, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 20))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 20))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 20)), val)
                }
{
                    let digit := and(shr(mul(21, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 21))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 21))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 21)), val)
                }
{
                    let digit := and(shr(mul(22, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 22))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 22))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 22)), val)
                }
{
                    let digit := and(shr(mul(23, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 23))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 23))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 23)), val)
                }
{
                    let digit := and(shr(mul(24, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 24))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 24))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 24)), val)
                }
{
                    let digit := and(shr(mul(25, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 25))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 25))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 25)), val)
                }
{
                    let digit := and(shr(mul(26, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 26))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 26))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 26)), val)
                }
{
                    let digit := and(shr(mul(27, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 27))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 27))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 27)), val)
                }
{
                    let digit := and(shr(mul(28, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 28))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 28))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 28)), val)
                }
{
                    let digit := and(shr(mul(29, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 29))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 29))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 29)), val)
                }
{
                    let digit := and(shr(mul(30, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 30))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 30))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 30)), val)
                }
{
                    let digit := and(shr(mul(31, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 31))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 31))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 31)), val)
                }
{
                    let digit := and(shr(mul(32, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 32))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 32))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 32)), val)
                }
{
                    let digit := and(shr(mul(33, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 33))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 33))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 33)), val)
                }
{
                    let digit := and(shr(mul(34, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 34))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 34))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 34)), val)
                }
{
                    let digit := and(shr(mul(35, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 35))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 35))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 35)), val)
                }
{
                    let digit := and(shr(mul(36, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 36))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 36))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 36)), val)
                }
{
                    let digit := and(shr(mul(37, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 37))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 37))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 37)), val)
                }
{
                    let digit := and(shr(mul(38, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 38))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 38))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 38)), val)
                }
{
                    let digit := and(shr(mul(39, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 39))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 39))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 39)), val)
                }
{
                    let digit := and(shr(mul(40, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 40))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 40))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 40)), val)
                }
{
                    let digit := and(shr(mul(41, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 41))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 41))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 41)), val)
                }
{
                    let digit := and(shr(mul(42, 3), d), 0x7)
                    let val := and(calldataload(add(wotsPtr, shl(4, 42))), N_MASK)
                    let chainBase := or(wotsAdrs, shl(32, 42))
                    val := chain(chainBase, val, digit)
                    mstore(add(0x80, shl(5, 42)), val)
                }
                let pkAdrs := or(shl(224, layer), or(shl(128, idxTree), or(shl(96, 1), shl(64, idxLeaf))))
                mstore(0x20, pkAdrs)
                mcopy(0x40, 0x80, 1376)
                let wotsPk := and(keccak256(0x00, 0x5A0), N_MASK)
                let authOff := add(countOff, 4)
                let treeAdrs := or(shl(224, layer), or(shl(128, idxTree), shl(96, 2)))
                let merkleNode := wotsPk
                let mIdx := idxLeaf
                let merklePtr := add(sigBase, authOff)
                {
                    let sibling := and(calldataload(add(merklePtr, shl(4, 0))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(0, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 1))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(1, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 2))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(2, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 3))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(3, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 4))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(4, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 5))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(5, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 6))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(6, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 7))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(7, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 8))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(8, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 9))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(9, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
{
                    let sibling := and(calldataload(add(merklePtr, shl(4, 10))), N_MASK)
                    let parentIdx := shr(1, mIdx)
                    mstore(0x20, or(treeAdrs, or(shl(32, add(10, 1)), parentIdx)))
                    let s := shl(5, and(mIdx, 1))
                    mstore(xor(0x40, s), merkleNode)
                    mstore(xor(0x60, s), sibling)
                    merkleNode := and(keccak256(0x00, 0x80), N_MASK)
                    mIdx := parentIdx
                }
                currentNode := merkleNode
                sigOff := add(authOff, 176)
            }
            valid := eq(currentNode, root)
            mstore(0x00, valid)
            return(0x00, 0x20)
        }
    }
}
