#!/usr/bin/env python3
"""Deterministic loop specialization of pinned C13; no cryptographic parameter changes."""
from pathlib import Path
import re
import hashlib
import argparse
root=Path(__file__).resolve().parents[1]
source=(root/'sphincs/vendor/SphincsC13Reference.sol').read_bytes()
assert hashlib.sha256(source).hexdigest() == 'fec5a9f19b202ab7aab6d7fcc3cd0a2b2e375edb943c62a569b3bb3e48ecdd16', 'Pinned upstream changed; re-review transformations'
s=source.decode()
s=s.replace('contract SphincsC13Asm','contract C13Verifier')
s=re.sub(r'//[^\n]*','',s)
# Use the hash address as induction variable: same steps, fewer loop operations.
s=s.replace('let steps := sub(7, digit)', '')
s=s.replace('for { let step := 0 } lt(step, steps) { step := add(step, 1) } {', 'for { let hashIdx := digit } lt(hashIdx, 7) { hashIdx := add(hashIdx, 1) } {')
s=s.replace('or(chainBase, add(digit, step))', 'or(chainBase, hashIdx)')
# Shared chain dispatcher specializes each possible base-8 digit.
start=s.index('                    for { let hashIdx')
end=s.index('                    mstore(add(0x80',start)
s=s[:start]+'                    val := chain(chainBase, val, digit)\n'+s[end:]
chain='function chain(base, val, digit) -> result { switch digit\n'
for digit in reversed(range(8)):
 chain += f'case {digit} {{\n'
 for step in range(digit,7):
  chain += f'mstore(0x20, or(base, {step})) mstore(0x40, val) val := and(keccak256(0, 0x60), 0xffffffffffffffffffffffffffffffff00000000000000000000000000000000)\n'
 chain += '}\n'
chain += 'result := val }\n'
s=s.replace('assembly {', 'assembly {\n'+chain,1)
# Sum the low 43 base-8 digits with broadword reductions. Each output
# lane doubles in width, so carries never cross a lane boundary.
start=s.index('                let digitSum := 0')
end=s.index('                if iszero(eq(digitSum',start)
reduction='let digitSum := and(d, '+hex((1<<129)-1)+')\n'
for width in (3,6,12,24,48,96):
 mask=sum(((1<<width)-1)<<i for i in range(0,256,2*width)) & ((1<<256)-1)
 reduction+=f'digitSum := add(and(digitSum, {hex(mask)}), and(shr({width}, digitSum), {hex(mask)}))\n'
# Last fold: 192 bits now contain the entire sum (43 digits < 64 lanes).
s=s[:start]+reduction+s[end:]
# Exact overlapping memmove; source/destination and length are unchanged.
for count in (7,43):
 old=f'for {{ let i := 0 }} lt(i, {count}) {{ i := add(i, 1) }} {{\n                    mstore(add(0x40, shl(5, i)), mload(add(0x80, shl(5, i))))\n                }}'
 if count==7: old=old.replace('                    mstore','                mstore').replace('\n                }','\n            }')
 assert old in s
 s=s.replace(old,f'mcopy(0x40, 0x80, {count*32})')
# Expand bounded loops inside out; retain the two-layer loop.
pattern=re.compile(r'for \{ let (\w+) := 0 \} lt\(\1, (\d+)\) \{ \1 := add\(\1, 1\) \} \{')
while True:
 matches=[m for m in pattern.finditer(s) if m.group(1)!='layer']
 if not matches: break
 m=matches[-1]; pos=m.end(); depth=1
 while depth:
  depth += (s[pos]=='{')-(s[pos]=='}'); pos+=1
 body=s[m.end():pos-1]
 s=s[:m.start()]+'\n'.join('{'+re.sub(r'\b'+m.group(1)+r'\b',str(i),body)+'}' for i in range(int(m.group(2))))+s[pos:]
s='// SPDX-License-Identifier: MIT\n// SPDX-FileCopyrightText: 2026 Nicolas Consigny <nicolas@ethereum.org>\n// Generated by sphincs/generate-verifier.py from pinned upstream; do not edit.\n// Terminal assembly uses scratch memory; intentionally NOT memory-safe.\n'+s
s=re.sub(r'\n\s*\n','\n',s)
s='\n'.join(line.rstrip() for line in s.splitlines()).strip()+'\n'
parser=argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args=parser.parse_args()
target=root/'src/sphincs/C13Verifier.sol'
if args.check:
 assert target.read_text()==s, 'Generated verifier is stale'
else:
 target.write_text(s)
